# Generated by Django 3.0.6 on 2020-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlikclient', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_name', models.TextField()),
                ('coordinateX', models.TextField()),
                ('coordinateY', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitch_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_id', models.TextField()),
                ('pitch_name', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('reservations', models.TextField()),
                ('ratings', models.TextField()),
            ],
        ),
    ]
