# Generated by Django 3.0.6 on 2020-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlikclient', '0004_logindata_pitch_pitch_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.TextField()),
                ('date', models.DateField()),
                ('start_hour', models.TextField()),
                ('end_hour', models.TextField()),
                ('pitch_id', models.TextField()),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='pitch_name',
            new_name='pitch_id',
        ),
    ]
