# Generated by Django 3.0.6 on 2020-06-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlikclient', '0005_auto_20200603_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_id', models.TextField()),
                ('pitch_name', models.TextField()),
                ('rating', models.TextField()),
            ],
        ),
    ]
