# Generated by Django 3.0.6 on 2020-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlikclient', '0007_auto_20200606_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='unchecked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
