# Generated by Django 3.0.6 on 2020-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orlikclient', '0008_rating_unchecked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='unchecked',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
